### ISSUE TITLE
Why is there a 1.5.2 tag with a different namespace?

### ISSUE THREAD

**Issue by drbyte** [404labfr/laravel-impersonate#103]
`> composer update`:
>  Updating lab404/laravel-impersonate (1.5.1 => 1.5.2): Downloading (100%)
Writing lock file
Generating optimized autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> `@php artisan package:discover --ansi`
>
>In ProviderRepository.php line 208:
>  **Class 'Lab404\Impersonate\ImpersonateServiceProvider' not found**
> Script `@php artisan package:discover --ansi` handling the post-autoload-dump event returned with error code 1

/vendor/lab404/laravel-impersonate/src/ImpersonateServiceProvider.php:
```php
<?php

namespace Bnb\Laravel\Impersonate;

use Illuminate\Auth\AuthManager;
use Illuminate\Auth\Events\Login;
use Illuminate\Auth\Events\Logout;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Event;
use Illuminate\View\Compilers\BladeCompiler;
use Bnb\Laravel\Impersonate\Guard\SessionGuard;
use Bnb\Laravel\Impersonate\Middleware\ProtectFromImpersonation;
use Bnb\Laravel\Impersonate\Services\ImpersonateManager;

/**
 * Class ServiceProvider
 *
 * @package Bnb\Laravel\Impersonate
 */
...
```

**Comment by MarceauKa** [comment]
I don't know why. That's a release from a fork. I just deleted it.

**Comment by drbyte** [comment]
Thanks
