### ISSUE TITLE
'Lab404\Impersonate\Models\Impersonate' not found

### ISSUE THREAD

**Issue by sevastyanovio** [404labfr/laravel-impersonate#111]
Hey there,

I'm getting a strange error after trying to update some other packages is my composer.json.
I've tried to roll back to my initial configs which worked previously, but it doesn't work even on them.

Details:

Getting this error: `'Lab404\Impersonate\Models\Impersonate' not found`
composer.json: `"lab404/laravel-impersonate": "^1.2",`

In file **vendor/lab404/laravel-impersonate/src/ImpersonateServiceProvider.php** for some reasons I have `namespace Bnb\Laravel\Impersonate;`

But previously it was – `namespace Lab404\Impersonate;`

Does anyone know what caused changes in namespace?

**Comment by MarceauKa** [comment]
Hi! Thank you for your feedback. I think you are using the ghost `1.5.2` release. Force an update to `1.5.1` or >= `1.6.0` and It'll fix the issue.

**Comment by chuckadams** [comment]
I have the exact same problem, and it's completely wedged our dev and CI.  What is a "ghost" release?  Has your repo been compromised?

**Comment by drbyte** [comment]
> I have the exact same problem, and it's completely wedged our dev and CI. 

Did you try the recommended fix? 
If not, what exact version of the package is your composer set to load? Why that version? Why not a newer one?

> What is a "ghost" release? 

Something amuck at Packagist back in January. Long time ago. Nothing brand new. Fixed a long time back.
https://github.com/404labfr/laravel-impersonate/issues/103
https://github.com/404labfr/laravel-impersonate/issues/98

> Has your repo been compromised?

Not at all.

**Comment by chuckadams** [comment]
Yes I took the recommended fix of pinning to 1.5.1 (we're running laravel 5.8) and that resolved the problem.  If it was fixed a long time back, I'm not seeing it, since as of now it still attempts to download that non-release.  Is there a way to tell composer to exclude just one particular version?
