### ISSUE TITLE
Composer loads version 1.5.2 - but there is not tagged version of 1.5.2 on the repo

### ISSUE THREAD

**Issue by Chalkin** [404labfr/laravel-impersonate#112]
When the version of the package is set to `^1.5.0` composer will load the version 1.5.2 for a laravel 5.x installation, which will result in loading some other code. Because this version has no tag or release on github, however this version is tagged on packagegist.

This inconsistency will result in composer loading some other code that is not related to the packge (different namespaces etc) and will break the laravel project that uses laravel-impersonate.

https://packagist.org/packages/lab404/laravel-impersonate#1.5.2

**Comment by drbyte** [comment]
Yes, there was a problem with 1.5.2. Ref #103 and #98 

Simply set your package to use `1.5.1` or `^1.6.0` depending on your app's needs. The latest is now `1.7.0`

**Comment by drbyte** [comment]
@MarceauKa, as reported, it looks like Packagist has once again got the 1.5.2 tag in it. You'll probably need to manually remove it again. Or maybe re-tag the 1.5.1 commit hash also as 1.5.3 (since 1.5.2 is "tainted", so to speak).

**Comment by Chalkin** [comment]
@drbyte Yes, for now we set it hard to 1.5.1 until we upgrade Laravel. But I guess it makes sence to remove 1.5.2 from packagegist, otherwise other people might get the same issue.

**Comment by MarceauKa** [comment]
@Chalkin Removed from Packagist
