### ISSUE TITLE
Multi guard support

### ISSUE THREAD

**Issue by vartakshreyas** [404labfr/laravel-impersonate#118]
Is multi guard support available in latest version?
I and trying to impersonate user from superadmin guard to businessadmin guard, but it take me to login page of business admin.
If i switched user between superadmin guard, its working fine.

Please help me to get out of this.
Thanks

**Comment by ctf0** [comment]
check https://github.com/404labfr/laravel-impersonate/pull/117/files

**Comment by MarceauKa** [comment]
Fixed in [1.7.2](https://github.com/404labfr/laravel-impersonate/releases/tag/1.7.2)
