### ISSUE TITLE
Customization support for the built in routes.

### ISSUE THREAD

**Issue by Kooser06** [404labfr/laravel-impersonate#119]
It would be handy to have a trait named "ImpersonatesUsers" and that trait contains the regular methods for the impersonating the user and leave user impersonation. This allows me to use that trait to a controller and I can redeclare the method to run some custom code. Because the website i am making is going to log moderation/administration activity so i would like to run a block of code along with those methods.

**Comment by drbyte** [comment]
If your goal is to "add additional logic" to the Impersonation process, you could just set up a Listener which you register to the `\Lab404\Impersonate\Events\TakeImpersonation` and/or `\Lab404\Impersonate\Events\LeaveImpersonation` events. 
Your logging can then happen inside the listener or in a job dispatched by the listener. You could even do notifications at that stage if necessary.
You may even want to register the same listener to the `\Illuminate\Auth\Events\Login` and/or `\Illuminate\Auth\Events\Logout` events in case those events need some logging or additional handling as well.

**Comment by Kooser06** [comment]
I forgot all about events, thank you @drbyte.
