### ISSUE TITLE
Add blade helper @canBeImpersonated

### ISSUE THREAD

**Issue by Konafets** [404labfr/laravel-impersonate#12]
Hey,

in my user list I dont want to show the Impersonate button for admins. At the moment I do this:

```php
@if((Auth::user()->id !== $user->id) && ($user->canBeImpersonated()))
    <a href="{{ route('impersonate', ['id' => $user->id]) }}" class="btn btn-xs btn-warning">Impersonate</a>
@endif
```

Unless I miss something, I think such a helper is a nice addition to this package.

**Comment by tghpow** [comment]
Hi.

Did you add the trait Impersonate to your user model ? 
Did you overwrite the canBeImpersonated() method ? How ?

**Comment by Konafets** [comment]
Yes, I have the trait and the method overridden like so

```php
/**
 * @return bool
 */
public function canBeImpersonated()
{
    return !$this->isAdministrator();
}
```

Just to be clear, my code above works as intended. I just thought it would be nice to have a blade helper for that.

**Comment by tghpow** [comment]
Ah sorry, i read too fast..

It's a good idea, if you want do a pull request.
Otherwise, we will do it ourselves on the occasion
