### ISSUE TITLE
canImpersonate and canBeImpersonated to accept an optional User

### ISSUE THREAD

**Issue by ziming** [404labfr/laravel-impersonate#124]
Feature Request: canImpersonate and canBeImpersonated to accept an optional User

This will allow for finer grain control of which user can or cannot be impersonated. Such as admins with a rank mechanism (e.g. admin level 1 cannot impersonate admin level 2 & 3)

I tried to make a PR but it turns out to be beyond me at the moment :/

**Comment by drbyte** [comment]
This already exists. Write it into your own application code by overriding the methods as described here: https://github.com/404labfr/laravel-impersonate#advanced-usage

**Comment by ziming** [comment]
Different. canImpersonate() and canBeImpersonated() doesn't accept a User as an argument. I'm looking for

canImpersonate(User $user = null) and canBeImpersonated(User $user = null)

did i miss something?

**Comment by drbyte** [comment]
It seems those methods are part of a trait, but not enforced by an interface/contract. Therefore it won't prevent you from changing the function signature by adding the parameters in your overridden methods. They would of course need to be optional, as in your examples.

Only caveat is that you couldn't use the Blade directives of the same name, as they already have different parameters for different reasons. But you could also override the Blade directives too by creating your own.
