### ISSUE TITLE
Blade directives not being parsed

### ISSUE THREAD

**Issue by wrabit** [404labfr/laravel-impersonate#126]
```
            @impersonating($guard = null)
                <a href="{{ route('impersonate.leave') }}">Leave impersonation</a>
            @endImpersonating
```

outputs 

![image](https://user-images.githubusercontent.com/5918271/101473987-ca571580-394a-11eb-8e30-9a4b979ed013.png)

in my view. 

- I have verified the library is installed ( I can successfully impersonate )
- `Lab404\Impersonate\ImpersonateServiceProvider::class` is in my config/app - providers[]
- Feels like I'm missing something simple

**Comment by MarceauKa** [comment]
Hi! Try this just after blade directives

```blade
@if(is_impersonating())
 Leave impersonation
@endif
```

**Comment by ctf0** [comment]
use it without args `@impersonating` unless the user can impersonate under more than one gate at the same time which i believe is not supported.

**Comment by wrabit** [comment]
@ctf0 I did, it was still same.

@MarceauKa's solution worked.
