### ISSUE TITLE
Can't leave impersonate

### ISSUE THREAD

**Issue by ajthinking** [404labfr/laravel-impersonate#130]
Im impersonating a User called 'Demo User'.

After going to `/impersonate/leave` Im still the Demo user (!).
Dumping in `leave` method of `InpersonateManager`:
```
dd($impersonated, $impersonator);
```
Gives 'Demo User' in both $impersonated and $impersonator.

What can be my issue here?

**Comment by ajthinking** [comment]
Unrelated to this repo

**Comment by ankkk** [comment]
what was your problem?

**Comment by ajthinking** [comment]
@ankkk, don't recall and lost access to repo unfortunately
