### ISSUE TITLE
Having problem installing the package. 

### ISSUE THREAD

**Issue by KhairulAzmi21** [404labfr/laravel-impersonate#135]
[
<img width="1440" alt="Screenshot 2021-03-12 at 11 40 04" src="https://user-images.githubusercontent.com/12378983/110888728-b941ea00-8327-11eb-9eaf-d9b19d433af8.png">
](url)

Hi, I can install because of guzzle problem . Im using laravel version 7.28.1 .

Anyone knows why?

**Comment by drbyte** [comment]
One approach:
`rm -rf vendor composer.lock` to delete all your existing dependency locks.
Then run `composer require .......` again.

**Comment by KhairulAzmi21** [comment]
> One approach:
> `rm -rf vendor composer.lock` to delete all your existing dependency locks.
> Then run `composer require .......` again.

Hi sir thanks for answering , I try do what you suggest still having problem . 
Apparently I able to solve it by added this line "guzzlehttp/guzzle": "^6.3", in my composer.json. I not sure why this happen .

**Comment by drbyte** [comment]
It's not related to this package. 
It is because of other packages your app requires. 

You could use this to investigate:
composer why guzzlehttp/guzzle
