### ISSUE TITLE
Extra cookies

### ISSUE THREAD

**Issue by AngelinCalu** [404labfr/laravel-impersonate#136]
With the package installed, signing in creates one extra cookie, signing out creates yet another one. Those are not cleared at any point, so they stack up quite quickly. 

Is this intended?

**Comment by drbyte** [comment]
I'm not experiencing this.

Perhaps you can share more information, such as the names of the cookies, and even your app code (or at least enough of a fresh app to replicate the symptoms).

**Comment by AngelinCalu** [comment]
The names are random. Something like "Gezto23OhbPLyYTsaPlLmAfgZuy5b7ZEDTP3Ibvq". 

I'm using Laravel Sanctum to authenticate the users on another subdomain. If it's a new thing then probably there's something wrong on my end. I'll double check.

**Comment by drbyte** [comment]
I haven't tried this package with Sanctum so can't speak to that factor.

**Comment by MarceauKa** [comment]
Please give more information about your codebase

**Comment by AngelinCalu** [comment]
Can't really remember what it was, but it was solved. 

This can be closed now. The app is in production for a few months.
