### ISSUE TITLE
Login as user with admin authorization

### ISSUE THREAD

**Issue by ErenJeager80** [404labfr/laravel-impersonate#138]
Hi,
Can I impersonate a user that is not admin but when that impersonated had admin authorization?

**Comment by drbyte** [comment]
You can impersonate whoever passes the rules you define in your `canImpersonate()` function.
You can further refine it by adding restrictions in  your `canBeImpersonated()` function.
https://github.com/404labfr/laravel-impersonate#advanced-usage

**Comment by ErenJeager80** [comment]
This is not my mean.
For example X is a customer, I want impersonate X, but when I Impersonated X, X had admin authorizations not customer authorizations

**Comment by drbyte** [comment]
Do you mean that you **want** to give admin rights to the customer **while** impersonating?

To do that, maybe you could check [isImpersonating](https://github.com/404labfr/laravel-impersonate#using-your-own-strategy) and add additional privileges if appropriate.

**Comment by matiazar** [comment]
Hi! How can I use that function.. Im administrator, I now impersonated a X user... but I need to know if Im a user or an administrator.

How can i check that? Auth::user()->isImpersonating() gives me an error

Call to undefined method App\Models\User::getImpersonatorId()

thanks!
