### ISSUE TITLE
Return value of Lab404\Impersonate\Services\ImpersonateManager::getSessionKey() must be of the type string, null returned

### ISSUE THREAD

**Issue by ssalem4pro** [404labfr/laravel-impersonate#148]
Hi, i just installed the plugin.
after that every time i logout or login, i get this error.
can someone guide me please?
i am using laravel 6.x
php 7.4

![image](https://user-images.githubusercontent.com/75600714/148055917-92a0de7e-a43d-4f4c-873d-af9e27dc4613.png)

**Comment by normimuc** [comment]
php artisan config:clear
php artisan view:clear

**Comment by ssalem4pro** [comment]
thanks, its working fine now. :)
