### ISSUE TITLE
Call to undefined method App\Models\User::impersonate()

### ISSUE THREAD

**Issue by magarrent** [404labfr/laravel-impersonate#178]
Hey there!

Maybe there is something missing in the documentation? I have to add `use Impersonate;` in my User model to use `->impersonate()` method.

Using Laravel 9

**Comment by drbyte** [comment]
Do you mean like this?
<img width="665" alt="Screen Shot 2023-03-30 at 4 39 26 PM" src="https://user-images.githubusercontent.com/404472/228959157-8148e221-1d4e-4eab-b20d-ca93d1b64dd8.png">

**Comment by magarrent** [comment]
> Do you mean like this? <img alt="Screen Shot 2023-03-30 at 4 39 26 PM" width="665" src="https://user-images.githubusercontent.com/404472/228959157-8148e221-1d4e-4eab-b20d-ca93d1b64dd8.png">

Lol! I'm officially blind hahhah
Sorry mate
