### ISSUE TITLE
How i should get the impersonating user details

### ISSUE THREAD

**Issue by rajjanorkar** [404labfr/laravel-impersonate#18]
Hi Team,

I like this package, it is really cool. But i have few questions as below.

1. In canBeImpersonated procedure in user model how i can get the current logged in user (agent) and the target user. in this procedure $this refers to the target user, and not currently logged in user (agent), this is required to check whether agent have access to target user profile.

2) I logged in as admin and then i impersonated another normal user, now @impersonating will return true. But how i can get the id of impersonating user (agent) here?

Thank you
Raj

**Comment by rajjanorkar** [comment]
I got the answer of second question : 

```
$manager = app('impersonate');
$manager->getImpersonatorId();
```
But dont know how to do the first one.

**Comment by MarceauKa** [comment]
For the first one, you simply can't. Except when you're taking impersonation, you can use built-in events.

**Comment by mushketer888** [comment]
1) You can use Auth::user()->id for logged in user + $this->id

**Comment by mushketer888** [comment]
Dont forget to check for guest account Auth::check()
