### ISSUE TITLE
Route::impersonate() returns Undefined offset: 0

### ISSUE THREAD

**Issue by gassius** [404labfr/laravel-impersonate#19]
Hi,

I am trying to use your package and I am having some trouble with the Macro Route.

When I incude the macro route in my routes/web.php `Route::impersonate();` I get this error:

ErrorException in Router.php line 1085: Undefined offset: 0

Any ideas on what I am doing wrong? Kind regards

**Comment by tghpow** [comment]
Hi,
Can you show us your web.php file please ?
Did you add the service provider ?

Thanks

**Comment by gassius** [comment]
Attached is the web.php file (renamed as txt for uploading)
[web.txt](https://github.com/404labfr/laravel-impersonate/files/1083400/web.txt)

I added to my app.php

`    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Package Service Providers...
         */
        Laravel\Tinker\TinkerServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        Sentry\SentryLaravel\SentryLaravelServiceProvider::class,

        // Impersonte package
        Lab404\Impersonate\ImpersonateServiceProvider::class
    ],
`
I am using Laravel v5.4.27

**Comment by drbyte** [comment]
>     Sentry\SentryLaravel\SentryLaravelServiceProvider::class,

I've seen others have troubles with this package when using Sentry.

**Comment by gassius** [comment]
Removing Sentry from providers does not seem to impact the issue.

**Comment by gassius** [comment]
Also, maybe related, maybe not. I not using the Macro Route, and I created a function in my UserController

```
    public function impersonate($id)
    {
      Auth::user()->impersonate($id);
    }
```
And created a route to it:

`Route::get('profile/impersonate/{id}', 'Common\UserController@impersonate')->name('admin.impersonate');`

When I click on the corresponding button I get this error:

BadMethodCallException

Call to undefined method Illuminate\Database\Query\Builder::impersonate()
in Builder.php (line 2450)
at Builder->__call('impersonate', array('2'))in Builder.php (line 1250)
at Builder->__call('impersonate', array('2'))in Model.php (line 1357)
at Model->__call('impersonate', array('2'))in UserController.php (line 167)
at UserController->impersonate('2')
at call_user_func_array(array(object(UserController), 'impersonate'), array('id' => '2'))in Controller.php (line 55)
at Controller->callAction('impersonate', array('id' => '2'))in ControllerDispatcher.php (line 44)

In my User model I included the trait as:

```
namespace App;

use App\Notifications\ResetPassword;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Lab404\Impersonate\Models\Impersonate;

class User extends Authenticatable
```

**Comment by Hornet-Wing** [comment]
I just hit the same issue during installation.

I eventually figured out that even though I did everything like @gassius and the instructions said, the issue was the Service Provider did not get loaded.

Solution:
Run the following commands to clear and re-load everything.
```
composer dump-autoload
php artisan optimize
php artisan config:clear
php artisan cache:clear
php artisan clear-compiled
```

Hope this saves someone some time!

**Comment by gassius** [comment]
I can confirm that the solution provided by @Hornet-Wing did solve the original problem. Alas, now I got some other BadMethodCallExceptions from the controller of this package. Thanks
