### ISSUE TITLE
Using Passport API not working returing false everytime

### ISSUE THREAD

**Issue by pankajsondagar** [404labfr/laravel-impersonate#199]
$customer = User::find($request->userId);

$data = Auth::user()->impersonate($customer);

Is there any way to make it working in API's?

**Comment by jose123v** [comment]
Maybe https://github.com/404labfr/laravel-impersonate/issues/183#issuecomment-2090775228

`TokenGuard` is `Macroable`
[laravel/passport/Guards/TokenGuard.php#L28-L30](https://github.com/laravel/passport/blob/8ea1dd41745c89769fd8c4b207c4739eea707e95/src/Guards/TokenGuard.php#L28-L30)
