### ISSUE TITLE
Fix read me type

### ISSUE THREAD

**Issue by elbakly** [404labfr/laravel-impersonate#20]
"a user" not "an user" and here is why

If the sound of the first letter is like Y then we use a, like a user, because u in user is like y. Otherwise, we use an, like an apple, an orange... Answer: ... For example, the word "user" is pronounced "yoozer" (the initial "y" sound acts as a consonant) so it must be preceded by an "a," not an "an."

**Comment by tghpow** [comment]
Hi,

thanks, you can do a PR for that.

**Comment by elbakly** [comment]
#21 Done

**Comment by tghpow** [comment]
Thanks :)
