### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by jesusephan** [404labfr/laravel-impersonate#22]
Hi,

I would like to know if you guys working on having this package be compatible with latest version of laravel which is 5.5?

Thanks

**Comment by drbyte** [comment]
Supports Laravel 5.5 since July 2017:
https://github.com/404labfr/laravel-impersonate/commits/master

Appears to work fine in my applications.

**Comment by jesusephan** [comment]
It seems new release was just published. Thanks

**Comment by drbyte** [comment]
@jesusephan You can close this issue now.
