### ISSUE TITLE
multiple guards

### ISSUE THREAD

**Issue by jozeflambrecht** [404labfr/laravel-impersonate#23]
Hi,

I am using multiple guards and I want the default guard (User model) to be able to impersonate an instance of a different guard (Student guard).

I added the trait to the Student model, but https://example.com/impersonate/take/1/view gives me a 404 error page.

Is multi guard supported?

Update:

if I put Route::impersonate(); in

```
Route::group(['middleware' => 'student_guest'], function() {
	Route::get('student', 'StudentAuth\LoginController@showLoginForm');
	//...
	Route::impersonate();
});
```
I am redirected to the login page for the student

if I put Route::impersonate(); in 

```
Route::group(['middleware' => 'student_auth'], function() {
	Route::post('student/logout', 'StudentAuth\LoginController@logout');
	//...
	Route::impersonate();
});
```

I get the 404 error page.

**Comment by jozeflambrecht** [comment]
No support for this?

**Comment by MarceauKa** [comment]
For now, multiple guards is not supported. But if you want to contribute feel free to make a PR :)

**Comment by drbyte** [comment]
Looking at the code earlier, I agree: multiple guards not supported right now. It's tied directly to the default guard:

https://github.com/404labfr/laravel-impersonate/blob/master/src/ImpersonateServiceProvider.php#L121

**Comment by sujalpatel022** [comment]
Hello,

It's possible with single Auth. because I was using single auth and I'm clicked on impersonating it redirects to login page.

I don't no what's the issue.

it's possible to conflict with  laravel auth middleware

**Comment by Vendin** [comment]
@MarceauKa take a look PR https://github.com/404labfr/laravel-impersonate/pull/58, please

**Comment by MarceauKa** [comment]
See the [1.4](https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.0)
