### ISSUE TITLE
laravel suporte 5.2

### ISSUE THREAD

**Issue by michelmelo** [404labfr/laravel-impersonate#24]
`composer require lab404/laravel-impersonate:1.1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for lab404/laravel-impersonate 1.1.0 -> satisfiable by lab404/laravel-impersonate[1.1.0].
    - lab404/laravel-impersonate 1.1.0 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.`

**Comment by MarceauKa** [comment]
This package is for Laravel >= 5.4.
