### ISSUE TITLE
Impersonate across subdomains

### ISSUE THREAD

**Issue by Wukatuff** [404labfr/laravel-impersonate#27]
Hi,

I'm trying to get a laravel impersonate working from one subdomain to another.
My admins are on their own environment, which both has a different domain and a different codebase from the user environment. My admins need to be able to impersonate users on the user environment, and preferably start that impersonate from the admin environment.

I've installed impersonate in both environments, and made sure to set up the session.php config such that they share a domain   (   .domainname.com ), they also share the same session driver etc.
Both do share the same database and user table.

Anyway, it doesn't seem to work. When admins use the impersonate option, they only appear to get impersonated on   admin.domainname.com   not on user.domainname.com. 

Is this something that is supported? And if so, what would I need to do to make it work?

**Comment by MarceauKa** [comment]
Hi! Thank you for your feedback.

It should works out of the box

Do you have different models for your users? (ex: Models\User and Models\Admin)
In this case you could use custom events to override how the manager fetch Users when taking and leaving impersonation.

**Comment by Wukatuff** [comment]
Seems it works great!

Turns out it was just because of config and installation errors on my end.  
For anyone else struggling with this, make sure to set your session driver and location so that they both point to the same thing, and don't forget to clear the laravel config cache. Additionally, just make sure everything for laravel-impersonate is perfectly set up in both code bases. In my case I was missing the changes to the routes file in one project, also make sure to use middlewareGroups=>['impersonate'], not middleware =>['impersonate']

**Comment by tghpow** [comment]
thanks for your feedback
