### ISSUE TITLE
Middleware  Protect From Impersonation

### ISSUE THREAD

**Issue by BAKTETE** [404labfr/laravel-impersonate#30]
i have this route in my `web.php`

```
Route::get('/candidat/candidature', function() {
    abort(404);
})->middleware('impersonate.protect');
```

after leaving the impersonation using :  `<a href="{{ route('impersonate.leave') }}">Leave impersonation</a>`
My route throw 404

**Comment by drbyte** [comment]
For `impersonate.leave`, the default redirect destination is 'back' to the previous URL (or to `/` with default config setting), which could result in a 404 if your routing throws one.

Did you publish the config file? You can configure the `leave_redirect_to` by specifying a desired destination route: https://github.com/404labfr/laravel-impersonate/blob/master/config/laravel-impersonate.php#L24

**Comment by BAKTETE** [comment]
@drbyte  
`leave_redirect_to` and 'take_redirect_to' is working fine 
the problem is when i want to acess the route as normal user not `impersonater` the route become inaccessible ignoring the check if user is `impersonater`

**Comment by BAKTETE** [comment]
Problem solved by declaring the `middleware` `impersonate.protect` inside the `constructor `of the controller
