### ISSUE TITLE
Did this actually get merged in as when I download via composer it's no different?

### ISSUE THREAD

**Issue by PilloryBarnDesign** [404labfr/laravel-impersonate#34]
https://github.com/404labfr/laravel-impersonate/pull/25/files 

The code in `src/ImpersonateServiceProvider.php` fixes an issue I'm having when I use Spatie's Laravel-Permission package, however when I require Laravel Impersonate package it doesn't bring down the code in the PR.

Was it missed? It says merged but I'm *really* confused by this.

Thanks in advance!

Andy

**Comment by drbyte** [comment]
Yes, #25 was merged. On Sept 29.

But the last "tagged" release was v1.2.1 on Sept 3: https://github.com/404labfr/laravel-impersonate/releases

So, you have 2 options:
a) wait for @MarceauKa to tag another release which includes the latest merges, 
or
b) Change your `composer.json` to use `"lab404/laravel-impersonate": "dev-master",` (which makes it always use the latest commits, whether officially tagged or not), and then run `composer update`

**Comment by PilloryBarnDesign** [comment]
@drbyte forgot about the `dev-master` flag! Thank you
