### ISSUE TITLE
Impersonation across Laravel projects

### ISSUE THREAD

**Issue by mattfaulk** [404labfr/laravel-impersonate#35]
Hi there,

I have seen another issue logged on this topic ( #27 ), however my scenario differs very slightly and wanted to know if what I am trying to do is achievable.

I have two Laravel (5.4) applications, using two different code bases and separate databases for authentication. This is essentially an admin and user portal. The domains are admin.domain.com and user.domain.com respectively.

To enable the admin portal to access information from the user portal, I have made certain models available to the admin portal, including the user model. I have the sessions logged to a shared database table and the session domain is the same for both environments.

I have implemented Impersonate in the admin portal, thinking this would insert the appropriate session information in to the database and enable me to authenticate as an impersonate user against the user portal. To start the impersonation process, I am call the impersonate route, passing the ID of the user to impersonate from a blade template. It doesn't seem to work though...

I don't know if I am missing something, or if this is simply not possible.

Any advice would be more than welcome.

Thanks in advance!

**Comment by mattfaulk** [comment]
I have ruled out authentication across sub-domains, this is well documented and should work without issue.

I believe the problem here is authentication across Laravel projects and possibly the session being restarted when accessing the 'other' Laravel project. I guess this is as a result of the 'web' middleware group.

When I attempt to impersonate another user, I successfully execute the impersonation function, the session is updated in the database to reflect the impersonated user, however, when redirecting to the other portal, I am presented with the login screen and a new null session is created.

**Comment by MarceauKa** [comment]
Closed for inactivity.
