### ISSUE TITLE
Way to detect if user is NOT impersonating

### ISSUE THREAD

**Issue by ToeiRei** [404labfr/laravel-impersonate#37]
How to solve that?

I'd suggest implementing an 'else' branch to do things like:

````
@impersonating
      <a href="{{ route('impersonate.leave') }}" Leave impersonation</a>
@notimpersonating
      <a href="{{ route('app.logout') }}" Logout</a>
@endnotimpersonating
```

in ImpersonateServiceProvider.php

**Comment by OwenMelbz** [comment]
@ToeiRei cant you just do?

```php
@impersonating
@else
@endImpersonating
```

**Comment by ToeiRei** [comment]
that didn't work out as it was my first try. I ended up with some messy php code in my blades

**Comment by OwenMelbz** [comment]
Hmm its working for me from what I can see

<img width="510" alt="home_blade_php_ _impersonate__vueimpersonate" src="https://user-images.githubusercontent.com/1094740/34325917-a2c36c40-e898-11e7-8e52-b000d577b674.png">

Then when logged in normally I see

<img width="510" alt="home_blade_php_ _impersonate__vueimpersonate" src="https://user-images.githubusercontent.com/1094740/34325921-c0dbae18-e898-11e7-888b-3df2f74223a6.png">

when impersonating i see

<img width="510" alt="home_blade_php_ _impersonate__vueimpersonate" src="https://user-images.githubusercontent.com/1094740/34325925-d157cac4-e898-11e7-8380-765739434170.png">

this is on a clean laravel 5.5 install

The native laravel `@else` directive just does returns an else from what i can see

<img width="510" alt="home_blade_php_ _impersonate__vueimpersonate" src="https://user-images.githubusercontent.com/1094740/34325942-24b4433c-e899-11e7-9695-8530afc447a6.png">

?

**Comment by legreco** [comment]
It works for me too. Thanks @OwenMelbz

**Comment by MarceauKa** [comment]
Closed for inactivity.
