### ISSUE TITLE
Logged in user set to impersonated user

### ISSUE THREAD

**Issue by meijdenmedia** [404labfr/laravel-impersonate#39]
For my application i have created multiple areas based on request URI:
> /admin/*
> /portal/*

From admin you can login as portal manager, which redirects to /portal and then you can see everything the portal manager can see.

But when logged in as portal manager I want to be the "normal" admin user in /admin/*. I want to be 2 users at the same time depending on the URI so I can have 2 tabs open in my browser.
I wrote a small Middleware which helps me with that.

```
if(get_current_project() === PROJECT_PORTAL) {
    // do nothing, keep being logged in as normal portal user or as impersonated portal user
    return $next($request);
}
// if project is admin or unknown..

// if impersonating ... auth once as the impersonated_by user
$impersonated_by = session()->get('impersonated_by');
if($impersonated_by !== null) {
    Auth::onceUsingId($impersonated_by);
}

return $next($request);
```

Most of the time this works perfectly .. but at some point, somehow, the current user is set to the impersonated user. I have no idea how to debug this and what is causing this.
> dd(request()->user()->id, session()->all());
> 9
> ["impersonated_by" => 9]

**Comment by MarceauKa** [comment]
Closed for inactivity.
