### ISSUE TITLE
impersonating twice

### ISSUE THREAD

**Issue by contentoo-tvdveen** [404labfr/laravel-impersonate#40]
Hi,

I managed to get the impersonation working correctly, but when I am impersonating a user, i cannot directly impersonate another user without leaving impersonation first.

So when i run:
/impersonate/take/2

All fine until I request:
/impersonate/take/3

I got the following error:
Symfony \ Component \ HttpKernel \ Exception \ HttpException
No message

/home/vagrant/laravelapps/dev.contentoo.com_react/contentoo_v3/vendor/laravel/framework/src/Illuminate/Foundation/Application.php
        return file_exists($this->storagePath().'/framework/down');
    }

 ```
/home/vagrant/laravelapps/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php
        return file_exists($this->storagePath().'/framework/down');
    }
 
    /**
     * Throw an HttpException with the given data.
     *
     * @param  int     $code
     * @param  string  $message
     * @param  array   $headers
     * @return void
     *
     * @throws \Symfony\Component\HttpKernel\Exception\HttpException
     */
    public function abort($code, $message = '', array $headers = [])
    {
        if ($code == 404) {
            throw new NotFoundHttpException($message);
        }
 
        throw new HttpException($code, $message, null, $headers);
    }
 
    /**
     * Register a terminating callback with the application.
     *
     * @param  \Closure  $callback
     * @return $this
     */
    public function terminating(Closure $callback)
    {
        $this->terminatingCallbacks[] = $callback;
 
        return $this;
    }
 
    /**
     * Terminate the application.
     *
     * @return void
     */

```

Is looks like the previous impersonation couldn't be removed..

Does somebody know what i'm doing wrong or is it a bug?

Thanks,
Thijs

**Comment by drbyte** [comment]
As far as I know It’s designed to require leaving impersonation first.

**Comment by contentoo-tvdveen** [comment]
Yes i noticed in the source code that it leaves impersonation first, but for some reason it is not working in my application.

**Comment by drbyte** [comment]
Are you first actually clicking to Leave Impersonation,
And then separately clicking to Take impersonation of a new user?

If that's not working then it seems there's a bug in your implementation.

**Comment by contentoo-tvdveen** [comment]
yes, so this sequence is working fine:
log in
/impersonate/take/2
/impersonate/leave
/impersonate/take/3
/impersonate/leave
etc.

But if i omit the 'leave' requests as follows:
log in
/impersonate/take/2
/impersonate/take/3

It will throw an error once i try to impersonate user 3.

**Comment by drbyte** [comment]
That's likely because the middleware is detecting that user `2` doesn't have permission to impersonate user `3`.
I believe that's by design.

I suppose you could override the middleware with your own that first detects whether you're already impersonating and then temporarily load up the user object for whoever is the impersonator and re-check whether they're allowed to `take` for the new user you're requesting.

**Comment by drbyte** [comment]
> I checked it but both users (2 and 3) have equal rights.

That's not the point.

You are probably user `1`.
But when you impersonate user `2` you don't have rights to impersonate anybody. So you can't impersonate user `3`. 
So, first you leave impersonation of user `2`, which returns you to being user `1`. Then you can impersonate user `3`.

**Comment by contentoo-tvdveen** [comment]
Thanks, but i couldn't make it work.

I ended up creating a small middleware class to intercept the /impersonate/take/{id} uri like this:

```
public function handle($request, Closure $next)
    {
        // intercept impersonate/take url
        $route = $request->route();

        if ($route->uri === 'impersonate/take/{id}') {
            app('impersonate')->leave();
        }

        return $next($request);
    }
```

It works but it feels a bit of a hack..
