### ISSUE TITLE
Impersonate with multi auth, is that possible?

### ISSUE THREAD

**Issue by DaviUchoa** [404labfr/laravel-impersonate#45]
is it possible for a user belonging to a guard('X') impersonate other from guard('Y')?

thanks in advance

**Comment by MarceauKa** [comment]
Hi! Look at PR #44 and PR #52.

**Comment by Vendin** [comment]
@MarceauKa when is it planned to release a new version?

**Comment by imanghafoori1** [comment]
You may use the github.com/imanghafoori1/laravel-masterpass
@DaviUchoa

**Comment by MarceauKa** [comment]
@imanghafoori1 @DaviUchoa already planned, see PR (tests missing)

**Comment by Vendin** [comment]
@MarceauKa here #58 I wrote tests, I am ready to make changes and add more tests, if necessary, if I get feedback and remarks from you

**Comment by MarceauKa** [comment]
See the [1.4](https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.0)
