### ISSUE TITLE
Use with a multi tenant system

### ISSUE THREAD

**Issue by eusouodaniel** [404labfr/laravel-impersonate#48]
I am developing a multi tenant system and I need this functionality, is it possible?

**Comment by nenads** [comment]
you can try my branch, i have no time to do test atm. but it seems to work on my project https://github.com/nenads/laravel-impersonate

**Comment by MarceauKa** [comment]
Not possible. Feel free to make a PR with tests.

**Comment by ctf0** [comment]
@MarceauKa can u tell me what would be needed to get this to work ? or what is the limitation ? especially if each tenant has its own db including the sessions table.

**Comment by koencg** [comment]
works with https://tenancyforlaravel.com/ (within the same tenant)
