### ISSUE TITLE
User impersonation using API Tokens

### ISSUE THREAD

**Issue by misoy** [404labfr/laravel-impersonate#61]
Hi. 

Is user impersonation possible using API Tokens by modifying this plugin?
Hopefully I can get an idea how to do it from brilliant developers.
I'm only new to laravel and I've been working this for weeks now :( 
I badly needed your help.

Thank you so much. God bless :)

**Comment by MarceauKa** [comment]
Hi, thank you for your feedback. Feel free to make a PR.

**Comment by MarceauKa** [comment]
Closed for inactivity.
