### ISSUE TITLE
Running in Laravel 5.8

### ISSUE THREAD

**Issue by jimmypuckett** [404labfr/laravel-impersonate#66]
In Laravel 5.4 the `fire` method for events was renamed to `dispatch`.  The `fire` method has been an alias to `dispatch` until 5.8.

https://laravel.com/docs/master/upgrade

I have a PR #65 that will address this issue.

**Comment by MarceauKa** [comment]
See https://github.com/404labfr/laravel-impersonate/tree/1.3.0
