### ISSUE TITLE
Conflict with session flash on Laravel 5.8

### ISSUE THREAD

**Issue by sangnguyenplus** [404labfr/laravel-impersonate#67]
Hi,

I found a bug on Laravel 5.8. After installing your package, session flash doesn't work anymore.

I've checked in the code and found a problem.
<img width="895" alt="screenshot at mar 04 22-32-38" src="https://user-images.githubusercontent.com/6972407/53743473-798cd000-3ecd-11e9-89fb-9dd2e141a8b2.png">

I commented this line then flash message works again.

File: /src/ImpersonateServiceProvider.php:140
```
$guard->setRequest($app->refresh('request', $guard, 'setRequest'));
```

Please check it, thanks!

**Comment by MarceauKa** [comment]
Hi, thank you for your feedback. Why it's closed?

**Comment by sangnguyenplus** [comment]
@MarceauKa, sorry, I've created issue faster my brain. The conflict issue is from my code, it's not because of your package :D I found it when I do some more test then I closed this issue.

Thank you!
