### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by tillkruss** [404labfr/laravel-impersonate#78]
Having the `impersonate` route as `GET` is quite risky.

Is there a best practice to prevent CSRF attacks?

**Comment by MarceauKa** [comment]
This behavior is meant to be used from an app admin with middleware and auth.

**Comment by tillkruss** [comment]
Admins are vulnerable to CSRF just like any user.

**Comment by MarceauKa** [comment]
So if that appears critical to you, feel free to implement your own logic. The `Route::impersonate()` is here for convenience.

You could simply make your own routes and use the base controller:
``
`php
Route::post('/impersonate/take/{id}/{guardName?}',
                '\Lab404\Impersonate\Controllers\ImpersonateController@take')->name('impersonate');
Route::post('/impersonate/leave',
                '\Lab404\Impersonate\Controllers\ImpersonateController@leave')->name('impersonate.leave');
```
