### ISSUE TITLE
Quirky issues leaving impersonation with certain accounts.

### ISSUE THREAD

**Issue by christonjones** [404labfr/laravel-impersonate#79]
I have the system operating within my application. I can impersonate and I can leave impersonation but only under specific circumstances.

Here is what works:
- Admin user can impersonate another Admin user and then click the Leave button and return successfully to their original account. 
- A team leader can impersonate another member of their team and then click the Leave button and return successfully to their original account.

Here is the problem, the part that does NOT work:
- Admin user can impersonate any team member just fine but upon clicking the Leave button they can NOT be returned to their original account. Instead, they are returned to the home page of the account user they are impersonating. 

What do I need to do to allow an Admin user to switch back to their original account after impersonating a non-admin user account?

Thanks

**Comment by drbyte** [comment]
Have you set the desired "leave" return-to URI in your config? `laravel-impersonate.leave_redirect_to`

https://github.com/404labfr/laravel-impersonate/blob/8804a1555b59710e5960a0dd4a35269145b1b4b6/config/laravel-impersonate.php#L33-L39

You could alternatively override the function that determines the URI:
https://github.com/404labfr/laravel-impersonate/blob/8804a1555b59710e5960a0dd4a35269145b1b4b6/src/Services/ImpersonateManager.php#L212-L224

**Comment by sgilberg** [comment]
Hi @christonjones I had a similar issue in my local implementation and found that it was because I had added Route::impersonate() within a route group that included additional admin middleware. Thus I could only leave the impersonation if I was an admin user, which left me stuck impersonating a non-admin user. I would double-check that the only middleware you are using is 'web.'

**Comment by christonjones** [comment]
Thanks for the tip @sgilberg, I hadn't thought of that. This might be the root of the issue. I did have it set up behind some routes that had additional admin middleware. That might be the solution. I quickly moved everything to just 'web' middleware, unfortunately, it did not magically fix the issue for me but I could have missed something. But your ideas have definitely given me an avenue to explore and work on. I have a feeling you are on the right path I just need a little more research into how it is affecting me. Thanks,

**Comment by christonjones** [comment]
@sgilberg, just wanted to follow up and let you know that your suggestion took me down the right path. Placing the routes outside the admin middleware was the key. There were a few other issues that I had to discover and modify related to it but I never would have gotten there if it hadn't been for your help and assistance. Thanks.
