### ISSUE TITLE
Remaining `dump` in ImpersonateManager.php

### ISSUE THREAD

**Issue by paul-thebaud** [404labfr/laravel-impersonate#81]
Hi.

A `dump` statement was added to the `ImpersonateManager.php` file on line 146 on [this commit](https://github.com/404labfr/laravel-impersonate/commit/1df8b57e1337bbccb89afdfb9cc45bc1865485e1#diff-f2974e766fe6270e2e430b81e35af6a9R134).

I don't why (because it is not on 1.4.0 tag or master branch), but when I update composer dependencies and get the 1.4.0 version of the package, I have this `dump` in the file...

Simple step to reproduce are:
```bash
# Make a new composer project.
$ mkdir test  && cd test

# Create an empty composer.json file.
$ composer init

# Require the package with 1.4.0 version.
$ composer require lab404/laravel-impersonate 1.4.0

# Open the file and check at line 146, here is the dump statement.
$ vi vendor/lab404/laravel-impersonate/src/Services/ImpersonateManager.php
```

Can you remove the statement and make a new release please?

Thanks.

**Comment by MarceauKa** [comment]
Fixed. https://github.com/404labfr/laravel-impersonate/releases/tag/1.4.1

**Comment by paul-thebaud** [comment]
Thx :D
