### ISSUE TITLE
Version for Laravel 5.3

### ISSUE THREAD

**Issue by leopinzon** [404labfr/laravel-impersonate#89]
Hello guys!, thanks a lot for this amazing package, 

One question regarding the versions compatibitlity; In the Master branch readme it says: **See release v1.1 for Laravel <= 5.4 support.** But the 1.0 and 1.1.1 readme settles the requirement as **Laravel >= 5.4**. 

Just wanted to know if this is a typo or if there is no support for Laravel 5.3 at all... 
Thanks a lot!

EDIT: Nop, just tried and either 1.0 nor 1.1.1 work with Laravel 5.3

**Comment by MarceauKa** [comment]
Yup, there's a typo in the readme. Laravel < 5.4 isn't supported.
