### ISSUE TITLE
TakeImpersonation and LeaveImpersonation events should not define Eloquent model typehint

### ISSUE THREAD

**Issue by riekelt** [404labfr/laravel-impersonate#91]
I use Doctrine in my Laravel application, so my user entity does not implement `\Illuminate\Database\Eloquent\Model`. 

Impersonation works fine with the doctrine entity, but the fired events require the implementation of `Illuminate\Database\Eloquent\Model`.

Since the user provider is known when fetching the user, the library could just use the `retrieveById()` function of the userprovider instead of the `findOrFail` which again depends on the eloquent model.

When a typehint is needed, please use `\Illuminate\Contracts\Auth\Authenticatable` since it has all the required functions to both retrieve the identifier (which is now done by `getKey` on the Eloquent model).

Would love to hear your thoughts on this.

**Comment by MarceauKa** [comment]
Hi and thank you for your feedback! It seems to be a very specific scenario. Feel free to make a PR (with tests)!
