### ISSUE TITLE
Tag 1.5.2 is non existing on GitHub but exists on Packagist

### ISSUE THREAD

**Issue by brunogaspar** [404labfr/laravel-impersonate#98]
Can you please remove the tag 1.5.2 from Packagist? Seems to point to an old release which is causing the Impersonate trait to not be found on the current namespace.

You can just go to https://packagist.org/packages/lab404/laravel-impersonate (being logged in as the maintainer account) and delete such tag if Packagist does not delete it automatically.

Thanks!

**Comment by az-iar** [comment]
+1 on this. I had to specify to use `1.5.1` instead to be able to use this package

**Comment by MarceauKa** [comment]
Hi, tag removed from packagist! (I did not see the last pull request came with a tag)

**Comment by brunogaspar** [comment]
Thanks, it's fixed for me :)
